# Generated by Django 4.0.3 on 2022-08-15 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userprofile_article_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='user_profile',
        ),
    ]
