# Generated by Django 4.0.3 on 2023-01-17 03:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_comment_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(related_name='liked_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='img',
            field=models.ImageField(blank=True, default='https://qph.cf2.quoracdn.net/main-qimg-2b21b9dd05c757fe30231fac65b504dd', null=True, upload_to='media'),
        ),
    ]
