# Generated by Django 4.0.3 on 2023-01-17 11:37

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_comment_likes_alter_userprofile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title_img',
            field=imagekit.models.fields.ProcessedImageField(upload_to='media'),
        ),
    ]
