# Generated by Django 4.0.3 on 2023-01-19 08:58

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_article_title_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='img',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='https://qph.cf2.quoracdn.net/main-qimg-2b21b9dd05c757fe30231fac65b504dd', null=True, upload_to='media'),
        ),
    ]
