# Generated by Django 4.0.3 on 2023-01-19 09:11

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_userprofile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumb_img',
            field=imagekit.models.fields.ProcessedImageField(default=1, upload_to='media'),
            preserve_default=False,
        ),
    ]
