# Generated by Django 4.0.3 on 2023-01-20 11:46

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_userprofile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='img',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
