# Generated by Django 4.0.3 on 2023-01-22 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_comment_is_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_liked',
        ),
    ]
