# Generated by Django 4.0.3 on 2023-01-28 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_comment_is_liked'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
