# Generated by Django 4.0.3 on 2023-01-28 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-date',)},
        ),
    ]
