# Generated by Django 4.0.3 on 2023-01-29 01:27

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_comment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='img',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='typer.webp', null=True, upload_to='media'),
        ),
    ]
